### ISSUE TITLE
Error when trying to use this

### ISSUE THREAD

**Issue by terrarier2111** [TkTech/Burger#38] opened 2021-10-13 15:32 UTC
I tried to get some information about 1.15.2, but i got the following error:
```
[threadexception@localhost Burger-master]$ python munch.py -d 1.15.2 --output items_out.json
Traceback (most recent call last):
  File "/home/threadexception/Downloads/mappings/Burger-master/munch.py", line 229, in <module>
    classloader = ClassLoader(path, max_cache=0, bytecode_transforms=[simple_swap, expand_constants])
  File "/usr/local/lib/python3.9/site-packages/jawa-2.2.0-py3.9.egg/jawa/classloader.py", line 50, in __init__
    self.update(*sources)
  File "/usr/local/lib/python3.9/site-packages/jawa-2.2.0-py3.9.egg/jawa/classloader.py", line 93, in update
    zf = ZipFile(source, 'r')
  File "/usr/lib64/python3.9/zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "/usr/lib64/python3.9/zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by Pokechu22** [comment] 2021-10-13 18:27
I can't reproduce this on my machine.

Try running `file 1.15.2.jar` and `sha1sum 1.15.2.jar`; if it says something other than "1.15.2.jar: Zip archive data, at least v2.0 to extract" and `e3f78cd16f9eb9a52307ed96ebec64241cc5b32d  1.15.2.jar` the file might have failed to download and is corrupt; you can delete it and try again.  (The `-d` option only downloads it once, and afterwards it re-uses the local file.)

**Comment by TkTech** [comment] 2022-02-10 20:49
Been awhile with no reply, closing.

**Closed by TkTech** 2022-02-10 20:49 UTC
